name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Normalize Workspace Permissions
        run: sudo chmod -R a+rwX "$GITHUB_WORKSPACE"
      - name: Build
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: "9.0"
          ocaml_version: "4.14-flambda"
          custom_script: |
            startGroup "Build"
              opam exec -- make
            endGroup
